spring:

  application:
    name: bets

  jpa:
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        access:
          strategy: property
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DRIVER}://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAM}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
    defaultSchema: ${DB_SCHEMA:main}
    change-log: ${CHANGE_LOG_PATH:classpath:db-migrations/changelog-master.xml}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_DRIVER}://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAM}

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.orm.boot.spi.ClassInfoImpl: DEBUG
    org.hibernate.metamodel.model.domain.internal: DEBUG